probably too little space for text
joepio/pauseai pull request #125
Opened 2024-03-24 10:58 UTC by Pato-desu

2024-03-24 11:13 UTC, Pato-desu commented
whaaat the places of the images change depending on the text? then I don't have idea how to fix some of them. @joepio fix them when you can

2024-03-24 11:29 UTC, Pato-desu commented
Btw:
- the images ARE NOT checked for copyright. Is that an important thing? I dont know how to check it
- some images and text I didnt take too much time to select them and edit them, so i wouldnt be surprised if there are better
-  this has the same conflict than the other PR, i just noticed
- trump being at the top it is in purpose for bipartisan support, but idk, im open to hear other opinions

2024-03-24 17:13 UTC, joepio commented
The images do need to be CC0 or checked before I can accept them I'm afraid

2024-03-24 18:18 UTC, Pato-desu commented
Okay, Ill see how can I do that

2024-03-24 19:52 UTC, Pato-desu commented
Is that the only type? you put a note in the Turing quote for other type of licenses, right?

2024-03-24 19:56 UTC, Pato-desu commented
@joepio let's say I don't find a CC picture of Paul Christiano, should I take the quote off the page?

2024-03-24 22:36 UTC, mrbreastly commented
Also, check preview here...  https://deploy-preview-125--pauseai.netlify.app/quotes
- Lots of images are way off center... (use `"padding": "#rem"` to align the text and images... e.g.     "padding": "3.6rem",     "padding": "1rem", etc)
- Text color is often unreadable (e.g. use    `"color": "black"` or `"color": "white"` depending on BG color.. etc

<img width="927" alt="image" src="https://github.com/joepio/pauseai/assets/61096713/0e04d4fc-35d9-4101-be67-688834805a33">
<img width="932" alt="image" src="https://github.com/joepio/pauseai/assets/61096713/06b7dfe2-2aef-422e-8d84-f54a70aa5fcd">

2024-03-24 22:55 UTC, mrbreastly commented
> * trump being at the top it is in purpose for bipartisan support, but idk, im open to hear other opinions

Yeah, might be worth including "Donald Trump, 45th President of the United States", "Joe Biden, 46th President of the United States"... so they're shown to be in chronological order?

2024-03-25 00:11 UTC, Pato-desu commented
> > whaaat the places of the images change depending on the text? then I don't have idea how to fix some of them. @joepio fix them when you can
> 
> Yeah, check preview here... https://deploy-preview-125--pauseai.netlify.app/quotes
> 
> * Lots of images are off center... (use `"padding": "#rem"` to align the text and images... e.g. try `"padding": "3.6rem"`,     `"padding": "1rem"`, etc)
> * Text color is often unreadable (e.g. use    `"color": "black"` or `"color": "white"` depending on BG color..)
> 
> <img alt="image" width="927" src="https://private-user-images.githubusercontent.com/61096713/316347710-0e04d4fc-35d9-4101-be67-688834805a33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjU2ODgsIm5iZiI6MTcxMTMyNTM4OCwicGF0aCI6Ii82MTA5NjcxMy8zMTYzNDc3MTAtMGUwNGQ0ZmMtMzVkOS00MTAxLWJlNjctNjg4ODM0ODA1YTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZjE5ZmU4M2Y0MWJmNzU2MTAwNmIzNmM0OTIyZjY5M2U5ODk1YTY1MWI4MzcwYmEzOWU5Mzc2M2M3MzYzMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oFHiAy7o_QNKFO1RXSOALtEyWSTHd5Re-zCysJYROjY"> <img alt="image" width="932" src="https://private-user-images.githubusercontent.com/61096713/316347822-06b7dfe2-2aef-422e-8d84-f54a70aa5fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjU2ODgsIm5iZiI6MTcxMTMyNTM4OCwicGF0aCI6Ii82MTA5NjcxMy8zMTYzNDc4MjItMDZiN2RmZTItMmFlZi00MjJlLThkODQtZjU0YTcwYWE1ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWQ2OTNiY2JkMjFkNGUzMjU2ODJiYmVlNGQzOTAxYjZmODBlZDlkZjIzMDdjMzVlZTNmMTM0NGE1OTRlNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1xWxuLk4ezvn1SnnSzTCaM4PbqgZ29cJNDD6PlXALVY">

Yeah, but first of all I have to find pictures without copyright

2024-03-25 18:06 UTC, mrbreastly requested changes

2024-03-25 18:06 UTC, mrbreastly commented on src/routes/quotes/data.json
> +    "author": "Statemen on AI risk,",
"Statemen on AI risk" -> "Statement on AI risk"

Fixed in the forked PR...  https://github.com/joepio/pauseai/pull/130

2024-03-25 18:06 UTC, mrbreastly commented on src/routes/quotes/data.json
> +    "text": "Get this wrong, and AI could make it easier to build chemical or biological weapons. Terrorist groups could use AI to spread fear and destruction on an even greater scale. Criminals coul
Awesome quote!  But, might be a little to long to fit on these small cards?  
- Maybe add a [..] to drop a little from the middle somewhere?
- Or, try to use padding to shift it around?

<img width="337" alt="image" src="https://github.com/joepio/pauseai/assets/61096713/64358682-3b19-45fa-a110-a17927410cad">

2024-03-25 18:06 UTC, mrbreastly commented on src/routes/quotes/data.json
> +    "text": "[...] just as AI has the potential to do profound good, it also has the potential to cause profound harm. From AI-enabled cyberattacks at a scale beyond anything we have seen before to A
These two might be better with white?

<img width="332" alt="image" src="https://github.com/joepio/pauseai/assets/61096713/1dbe4691-3704-403c-a472-fc89ce98d21f">

2024-03-25 18:14 UTC, mrbreastly commented on src/routes/quotes/data.json
> +    "text": "Artificial intelligence is the future, not only for Russia, but for all humankind. It comes with colossal opportunities, but also threats that are difficult to predict. Whoever becomes t
https://github.com/joepio/pauseai/pull/134

2024-03-25 18:22 UTC, mrbreastly requested changes

2024-03-25 18:22 UTC, mrbreastly commented on src/routes/quotes/data.json
> +    "text": "AI poses a long-term global risk. Even its own designers have no idea where their breakthrough may lead. I urge [the UN Security Council] to approach this technology with a sense of urge
This one might be too long too?  Would be more readable if the text didn't overlap with the image?

<img width="337" alt="image" src="https://github.com/joepio/pauseai/assets/61096713/6bbb60db-858b-430e-adb1-9fd0c1f59f25">

2024-03-25 18:26 UTC, mrbreastly commented
Hey @Pato-desu, good quotes! I made some suggestions here.  I don't have access to update this branch directly. If I get some time later I'll see if I can make a fork of your branch here and apply some fixes and a new PR, for this branch...

2024-03-30 01:21 UTC, merged

2024-03-30 01:26 UTC, Pato-desu commented
Things left to do:
- [ ] Add some more quotes. Mainly from the CEOs
- [ ] Add more "placeholder" pictures like the one with the chinese flag
- [ ] Maybe add more smooth transitions between quotes and pictures