Bunch of added things to the risk page
joepio/pauseai pull request #84
Opened 2024-01-24 19:44 UTC by Pato-desu

I think some sections can be a lot more subjective that what I've seen on the website or that at least I haven't seen other people talk about them (probably because they are not as important as x-risks), so others could not agree with them, so you should read them closely.

Also it could be written not very well and with a bunch of grammatical errors, so feel free to change it as you would prefer. I think it's better to have them amateurish written (and without links) than to not have them at all.

2024-01-28 18:19 UTC, joepio requested changes

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Deepafakes not only can steal famous people identities and create disinformation, but can impersonate you too.
Deepfakes

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Anyone with photos, videos, or audios of someone and enough knowledge, can create deepfakes of them (soon in real time and with high quality) and use them to commit fraud, harass them, or create sexu
Can you add sources here?

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Generative AI models do not just copy the biases from their training data, [they amplify them](https://www.bloomberg.com/graphics/2023-generative-ai-bias/)..
Why the added dot? Might be typo?

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +And is difficult to predict what jobs are going to be the ones replaced first. They could leave you unemployed and without an income no matter how much time, money and energy you spent on getting the
Every line should have an enter. Also, the fist "and" is gramattically off I think

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +
Perhaps at the end make the bridge to x-risk. In a way, x-risk is the ultimate disempowerment.

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Whether AIs centralize power around certain actors or not, and even if single systems don't optimize strongly for any particular measure that we cannot steer or fix, we could lose our power to take d
Long and abstract sentence, bit hard to parse. Maybe break it down.

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Those systems would have more input from other systems than from humans, and, if we cannot coordinate quick enough or we lack crucial knowledge about the functioning of these systems, we could end up
Again maybe a tad hard to follow. I get what you're saying, but to a newby it needs some guidance. Not sure how though.

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +## Present dangers
Good to split the sections. Maybe the distinction does warrant some explanation?

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Deepafakes not only can steal famous people identities and create disinformation, but can impersonate you too.
Perhaps first explain what they are, very briefly?

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +Anyone with photos, videos, or audios of someone and enough knowledge, can create deepfakes of them (soon in real time and with high quality) and use them to commit fraud, harass them, or create sexu
I think we can already link to examples, e.g. https://time.com/6565446/biden-deepfake-audio/

2024-01-28 18:19 UTC, joepio commented on src/posts/risks.md
> +### Fake news, polarization and democracy
I think the polarization risk is tied to narrow AI in social media. It should probably deserve a link / explanation.

2024-01-28 19:18 UTC, Pato-desu commented on src/posts/risks.md
> +Anyone with photos, videos, or audios of someone and enough knowledge, can create deepfakes of them (soon in real time and with high quality) and use them to commit fraud, harass them, or create sexu
I'll add that link, and yeah, we could add sources everywhere, in each section. right now i'm kinda busy

2024-01-28 19:19 UTC, Pato-desu commented on src/posts/risks.md
> +## Present dangers
I think it's pretty self-explanatory, feel free to add one if you want though

2024-01-28 20:30 UTC, Pato-desu commented on src/posts/risks.md
> +### Fake news, polarization and democracy
I understand what you mean, I don't think I wrote about polarization, but really fake social media content and fake news should go hand and hand together. It's not that people see stuff that they don't know if it's true or and not knowing what it's true make them want to overcome democracy, like this section seems to imply. It's that fake info could lead to distrust of institutions that could lead to people wanting to overcome democracy.

2024-01-28 23:57 UTC, Pato-desu commented on src/posts/risks.md
> +Those systems would have more input from other systems than from humans, and, if we cannot coordinate quick enough or we lack crucial knowledge about the functioning of these systems, we could end up
yeah, it's complicated to explain disempowerment. check the changes that I did now

2024-01-28 23:57 UTC, Pato-desu commented on src/posts/risks.md
> +Deepafakes not only can steal famous people identities and create disinformation, but can impersonate you too.
done

2024-01-28 23:58 UTC, Pato-desu commented on src/posts/risks.md
> +
I ended up putting x-risks above because it's simpler and easier to explain the other stuff afterwards kinda

2024-01-28 23:59 UTC, Pato-desu commented
welp, I made some changes. Tell me if they are not enough

2024-01-29 07:29 UTC, joepio approved these changes

2024-01-29 07:29 UTC, merged

2024-01-29 07:29 UTC, joepio commented
Great, thanks!